
FROM baselinux:01
MAINTAINER Mohan Singh and Naresh Sherwal

# Installing mysql and dependent libraries
RUN apt-get update 
RUN apt-get -y install libmysqlclient-dev mysql-client-5.5

CMD ["/bin/bash"]
